server:
  port: 10003

############################################################
#
# 配置数据源信息
#
############################################################
spring:
  datasource:                                           # 数据源的相关配置
#    url: jdbc:mysql://localhost:3306/foodie-shop-dev?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false&useUnicode=true
#    password: briup
#    拆分微服务可以考虑拆分数据源到独立的database instance， 或者独立schema
    url: jdbc:mysql://192.168.163.145:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: root
  redis:
    #Redis 的单机单实例
    database: 1
    host: 192.168.163.155
    port: 6379
    password: imooc
    # Redis哨兵模式
#    database: 1
#    password: imooc
#    sentinel:
#      master: imooc-master
#      nodes: 192.168.163.153:26379,192.168.163.154:26379,192.168.163.155:26379
    #Redis 集群模式
#    password: imooc
#    cluster:
#      nodes: 192.168.163.201:26379,192.168.163.202:26379,192.168.163.203:26379,192.168.163.204:26379,192.168.163.205:26379,192.168.163.206:26379



############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# Ribbon 全局配置,单位毫秒
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 3000
#Ribbon 指定服务配置超时判定，优先级更高
foddie-user-service:
  ribbon:
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    OkToRetryOnAllOperations: true

#Feign的超时判定，优先级高于Ribbon
feign:
  client:
    config:
      # 全局默认配置
      default:
        connectTimeout: 1000
        readTimeout: 3000
      # 优先级比上面的高
      foddie-user-service:
        connectTimeout: 1000
        readTimeout: 5000


